project:
  type: website
  resources:
    - resources/Cv.pdf
  output-dir: docs
    
website:
  title: "Tommaso Ghilardi"
  description: "I hold a Ph.D. in developmental science with a strong focus on analyzing complex, real-world data, exploring the stories behind the data, and deriving actionable insights through advanced statistical analysis and computational modeling. I am passionate about sharing knowledge and translating detailed analyses into clear, accessible insights for diverse audiences."
  site-url: "https://tommasoghilardi.github.io"
  
  
  # Utilities
  back-to-top-navigation: true
  page-navigation: true
  reader-mode: false
  
  search:
    location: sidebar
    type: textbox
  
  
  navbar:
    background: dark
    
    right:
      - href: CV.qmd
        text: CV
      - href: Listing.qmd
        text: Blog
  
  sidebar:
    title: " "
    style: "floating"
    border: true
    align: center

    contents:
      - section: "General"
        contents:
          - posts/general/InstallPython.qmd

      - section: "Stats:"
  
  

format:
  html:
    theme: _style.scss
    mainfont: 'Arial'
    
    toc: true
    toc-expand: 4

    # Code variables
    code-fold: false
    code-copy: true
    code-link: true
    code-overflow: scroll
    code-tools:
      source: true
      toggle: true
      caption: none
    highlight-style: zenburn
    code-block-background: true
    code-block-border-left: "#00B3B3"
    
editor: visual

